### ISSUE TITLE
About encrypt any file

### ISSUE THREAD

**Issue by smileLikeSun** [stefano81/dcpabe#36]
When I try to encrypt the specified file, the decrypted data is always a fixed length byte stream, resulting in decryption failure. Could you give me some guidance。

// Message message = DCPABE.generateRandomMessage(gp);
Path path = Paths.get("src/test/java/textTest/test.txt");
byte[] ss = Files.readAllBytes(path);
Message msg = new Message(ss);

**Comment by stefano81** [comment]
Thanks for point out the issue, working on it.

**Comment by stefano81** [comment]
Hi @smileLikeSun,
the encryption of message is limited to the size of elements of the Field. This means that messages longer than a certain size (depending on the initialization and field selection) cannot be encrypted directly.
This is an implementation choice, as DCPABE encryption/decryption is a slow process when compared to other schemas.
The recommended pattern is to follow the process presented in `ProgrammaticAccessTest#testMessageCorrectlyDecrypted`.
