### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by lyaice** [stefano81/dcpabe#39]
where can I check the corresponding papers?

**Comment by stefano81** [comment]
Hi @lyaice S. Braghin, J. Tan Teck Yong, R. Sharma and A. Datta: "PriSM: A Private Social Mesh for Leveraging Social Networking at Workplace". CoRR abs/1206.1653 (2012) is available at https://arxiv.org/abs/1206.1653
Lewko's paper is available at https://eprint.iacr.org/2010/351
